ansible_ssh_user: arkuser
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
ansible_host_key_checking: false
ark_session_name: "session"
ark_server_password: ""
ark_number_players: 70
ark_admin_password: "password"
ark_server_map: "Extinction"